/*
 * Autogenerated file, do not  edit
 * Tue Aug  4 16:13:41 BST 2020
 * -------------------------------
 */


/**
 * @ingroup location
 *
 * @brief Locate nearest point on an element
 *
 * Locate the nearest point on an element using the iterative
 * algorithm of Li X, Wu Z, Pan F et al. A geometric strategy
 * algorithm for orthogonal projection onto a parametric
 * surface. https://dx.doi.org/10.1007/s11390-019-1967-z
 *
 * @param xe element node coordinates;
 * @param xstr stride between x coordinates of element nodes;
 * @param ne number of element nodes;
 * @param xf field point;
 * @param sn on exit reference element coordinate of nearest point;
 * @param tn on exit reference element coordinate of nearest point;
 * @param p1 physical location of nearest point;
 * @param tol tolerance for iteration;
 * @param nimax maximum number of iterations;
 * @param kn curvature at nearest point.
 *
 * @return number of iterations
 **/

gint qbx_element_nearest_point(gdouble *xe, gint xstr,
						  gint ne,
						  gdouble *xf, 
						  gdouble *sn, gdouble *tn, 
						  gdouble *p1, gdouble tol,
						  gint nimax, gdouble *kn) ;

/**
 * @ingroup quadrature
 *
 * @brief Integration of Laplace potential on triangular element, with
 * field point on element ("self term")
 *
 * @param xe element node coordinates;
 * @param xstr stride between x coordinates of element nodes;
 * @param ne number of element nodes;
 * @param s0 reference element coordinate of evaluation point;
 * @param t0 reference element coordinate of evaluation point;
 * @param q quadrature rule nodes and weights;
 * @param nq number of entries in \a q;
 * @param oq order of \a q (highest order polynomial integrated exactly);
 * @param Nmax maximum order of expansion;
 * @param dmax maximum recursin depth in adaptive quadrature;
 * @param tol error tolerance;
 * @param Is on exit integrated single layer potential for nodal shape 
 * functions;
 * @param istr stride in \a Is (ignored for now);
 * @param Id on exit integrated double layer potential for nodal shape 
 * functions;
 * @param dstr stride in \a Id (ignored for now);
 * @param work workspace.
 *
 * @return 0 on success
 *
 **/

gint qbx_triangle_laplace_self_quad(gdouble *xe,
						       gint xstr,
						       gint ne,
						       gdouble s0,
						       gdouble t0,
						       gdouble *q,
						       gint nq, gint oq,
						       gint Nmax, gint dmax,
						       gdouble tol,
						       gdouble *Is, gint istr,
						       gdouble *Id, gint dstr,
						       gdouble *work) ;

/**
 * @ingroup location
 *
 * @brief Locate nearest point on an element
 *
 * Locate the nearest point on an element using the iterative
 * algorithm of Li X, Wu Z, Pan F et al. A geometric strategy
 * algorithm for orthogonal projection onto a parametric
 * surface. https://dx.doi.org/10.1007/s11390-019-1967-z
 *
 * @param xe element node coordinates;
 * @param xstr stride between x coordinates of element nodes;
 * @param ne number of element nodes;
 * @param xf field point;
 * @param sn on exit reference element coordinate of nearest point;
 * @param tn on exit reference element coordinate of nearest point;
 * @param p1 physical location of nearest point;
 * @param tol tolerance for iteration;
 * @param nimax maximum number of iterations;
 * @param kn curvature at nearest point.
 *
 * @return number of iterations
 **/

gint qbx_element_nearest_point_f(gfloat *xe, gint xstr,
						  gint ne,
						  gfloat *xf, 
						  gfloat *sn, gfloat *tn, 
						  gfloat *p1, gfloat tol,
						  gint nimax, gfloat *kn) ;

/**
 * @ingroup quadrature
 *
 * @brief Integration of Laplace potential on triangular element, with
 * field point on element ("self term")
 *
 * @param xe element node coordinates;
 * @param xstr stride between x coordinates of element nodes;
 * @param ne number of element nodes;
 * @param s0 reference element coordinate of evaluation point;
 * @param t0 reference element coordinate of evaluation point;
 * @param q quadrature rule nodes and weights;
 * @param nq number of entries in \a q;
 * @param oq order of \a q (highest order polynomial integrated exactly);
 * @param Nmax maximum order of expansion;
 * @param dmax maximum recursin depth in adaptive quadrature;
 * @param tol error tolerance;
 * @param Is on exit integrated single layer potential for nodal shape 
 * functions;
 * @param istr stride in \a Is (ignored for now);
 * @param Id on exit integrated double layer potential for nodal shape 
 * functions;
 * @param dstr stride in \a Id (ignored for now);
 * @param work workspace.
 *
 * @return 0 on success
 *
 **/

gint qbx_triangle_laplace_self_quad_f(gfloat *xe,
						       gint xstr,
						       gint ne,
						       gfloat s0,
						       gfloat t0,
						       gfloat *q,
						       gint nq, gint oq,
						       gint Nmax, gint dmax,
						       gfloat tol,
						       gfloat *Is, gint istr,
						       gfloat *Id, gint dstr,
						       gfloat *work) ;

